### ISSUE TITLE
menegiñ an dud neuent labouret

### ISSUE THREAD

**Issue by MJouitteau** [gweltou/roadennou#1]
Gwelout a ran peus kavet un doare da venegiñ ar meta-roadennoù. Mat eo ober kement-se.
Traoù a zo da ouzhpennañ.
Mouezh Laors Skavenneg zo war destenn Korin ar Merv. 
Mouezh Brendan-Budok Durand-Le Ludec zo bet treuzskrivet gant Manon Jouitteau, Yf Le Gall ha me (2023). 
Testenn BCDia zo da venegiñ gant an den a gomz, an dastumer hag an treuzskrivour (Francis Favereau). Francis noa asantet e vefe implijet an dafar. Lors Jouin noa asantet ivez gant ma ne vo ket graet un implij kenwerzhel. Goulennet en doa gant ar gevredigezh komzou brezhoneg ivez. 
Talvezout a ra neuze kement ha Creative Commons BY-NC-SA war teuliad komzou brezhoneg BCDia a-bezh.

**Comment by gweltou** [comment]
Trugarez !
Ouzhpennet em eus an titouroù-se. Lâr din ma veles traoù all a vank.
