### ISSUE TITLE
meta-roadennoù

### ISSUE THREAD

**Issue by MJouitteau** [gweltou/roadennou#2]
Klask a ran un doare da vuzuliañ an danvez roet amañ evit hen menegiñ [amañ](https://entrelangues.modyco.fr/index.php/Breton#corpus_align%C3%A9_audio).

**Comment by gweltou** [comment]
Lakaat a rin ur golonenn nevez gant padelezh pep doser a-benn nebeut.
Na jed ket se dre zorn ! Ober a rin ur skript evit muzuliañ-se en un doare aotomatel (kresk a raio ingal emichañs).
Dibenn bloavezh laouen dit !
